### ISSUE TITLE
Release for Scala.js on 3.0.0-M3?

### ISSUE THREAD

**Issue by darkfrog26** [com-lihaoyi/sourcecode#100]
It looks like a release was made a few days ago for 3.0.0-M3 but it would appear that there was no release made for Scala.js on 3.0.0-M3?

**Comment by darkfrog26** [comment]
What do I need to do to get a response on this?

**Comment by lolgab** [comment]
Hi @darkfrog26,
Mill didn't support Scala.js until some days ago. Now it does and I'm going through all the com-lihaoyi projects to publish them for Scala 3.0.0-RC1 and Scala.js 1.4.0

**Comment by darkfrog26** [comment]
No worries, I published it under my fork https://github.com/outr/sourcecode with Scala.js 1.5.0 after I got tired of waiting for any response.
