### ISSUE TITLE
sourcecode.Name does not capture back ticked `macro` keyword in Scala3 (200USD Bounty)

### ISSUE THREAD

**Issue by carueda** [com-lihaoyi/sourcecode#120]
Scastie: https://scastie.scala-lang.org/carueda/NIAVkP82Rd2RVusUXRZMGQ/13

In short, applying:

```scala
def keyword(implicit name: sourcecode.Name): String = name.value
```

to back ticked `macro`:

```scala
val `macro` = keyword
```

results in capturing something else, apparently the name of the enclosing environment, but not the val's name itself.

Other Scala keywords seem to be captured just fine.

Haoyi: To incentivize contribution, I'm putting a 200USD bounty on resolving this ticket. This is payable via bank transfer, and at my discretion in case of ambiguity. The acceptance criteria is a PR fixing this issue and updates to our test infrastructure to validate the fix

**Comment by carueda** [comment]
though nobody seems to care, fwiw, just reproduced this with Scala 3.1.3 and sourcecode 0.3.0

![Screen Shot 2022-08-02 at 8 01 07 PM](https://user-images.githubusercontent.com/556505/182515015-099d18ef-68e3-4e53-bce7-759373be1b11.png)

**Comment by KacperFKorban** [comment]
Hi, I'd like to take a crack at it

**Comment by lihaoyi** [comment]
@KacperFKorban go for it, no need to ask permission!

**Comment by carueda** [comment]
awesome.
